// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  DNF

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Document ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Document ) UnmarshalJSON([]byte) error { return nil }
func ( Document ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Document ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Document *Document
