package util

const(
	/**
     * 错误代码键
     */
	RET_STATUS_KEY = "status"

	/**
     * 错误信息键
    */
	RET_REASON_KEY = "reason"
	RET_STATUS_400 = "INVALID_ARGUMENT"
    RET_STATUS_500 = "INTERNAL_ERROR"
    RET_STATUS_200 = "OK"
    RET_STATUS_401_1 = "UNAUTHORIZED"
    RET_STATUS_401_2 = "ACCOUNT_INVALID"
    RET_STATUS_401_3 = "SIGN_INVALID"
    RET_STATUS_403_1 = "RATE_LIMIT_EXCEEDED"
    RET_STATUS_403_2 = "NO_PERMISSION"
    REDIS_DB_SARA = 10
    REDIS_DB_BDP_OFFLINE = 4
    REDIS_DB_BDP_REALTIME = 3
	REDIS_DB_DM = 15

	/**
	* 树结构中子节点的名称
	*/
	KEY_CHILDREN = "children"

	/**
     * 日期时间格式
     */
	DATE_FORMAT = "yyyyMMdd"
    DATEIIME_FORMAT = "yyyyMMdd HH:mm:ss"
    TIMESTAMP_FORMAT = "yyyy-MM-dd HH:mm:ss"
    TIME_FORMAT = "HH:mm:ss"
    TIME_FORMAT_FOR_AD = "yyyy-MM-dd"


	AD_BDP_SENSEAR_HOUR_RATIO = "AD_BDP_SENSEAR_HOUR_RATIO:"
    AD_BDP_SENSEAR_USER_INFO = "AD_BDP_SENSEAR_USER_INFO:"
    SARA_KEY_AD_EX_INFO = "SARA_KEY_AD_EX_INFO:"
    SARA_KEY_USER_AD_SHOW = "SARA_KEY_USER_AD_SHOW:"
    SARA_KEY_AD_BASEDATA = "SARA_KEY_AD_BASEDATA:"
    SARA_KEY_AD_PACKAGE_BASEDATA = "SARA_KEY_AD_PACKAGE_BASEDATA:"
    SARA_KEY_USER_TAGS = "SARA_KEY_USER_TAGS:"
    FANS_COUNT = "FANS_COUNT:"

	SARA_KEY_AD_COST_DATA = "SARA_KEY_AD_COST_DATA:"
    SARA_KEY_ADPLAN_COST_DATA = "SARA_KEY_ADPLAN_COST_DATA:"
    SARA_KEY_ADVERTISER_COST_DATA = "SARA_KEY_ADVERTISER_COST_DATA:"

    AD_BDP_SENSEAR_ADPLAN_COST_DATA = "AD_BDP_SENSEAR_ADPLAN_COST_DATA:"
    AD_BDP_SENSEAR_ADVERTISER_COST_DATA = "AD_BDP_SENSEAR_ADVERTISER_COST_DATA:"
    SARA_KEY_AD_POST_DATA = "SARA_KEY_AD_POST_DATA:"
    SARA_KEY_AD_STATISTICS_DATA = "AD_BDP_SENSEAR_AD_STATISTICS_DATA:"
    AD_DM_SENSEAR_AD_STATIC_CPT = "AD_DM_SENSEAR_AD_STATIC_CPT:"
    AD_DM_SENSEAR_AD_STATIC_CPM = "AD_DM_SENSEAR_AD_STATIC_CPM:"
    AD_DM_SENSEAR_AD_REALTIME_CPT = "AD_DM_SENSEAR_AD_REALTIME_CPT:"
    AD_DM_SENSEAR_AD_REALTIME_CPM = "AD_DM_SENSEAR_AD_REALTIME_CPM:"
    AD_DM_SENSEAR_AD_PRELOAD = "AD_DM_SENSEAR_AD_PRELOAD:"
    AD_MODE_CPT_AD_NUM = "AD_MODE_CPT_AD_NUM"

    STATUS_AD_ENABLE = 0
    STATUS_AD_DISABLE = 1
    API_VERSION_NEW = 1
    API_VERSION_OLD = 0
    AD_MODE_TEN_SECOND = 2
    AD_MODE_THREE_SECOND = 5
    TYPE_COST_CPC = "1"
    TYPE_COST_CPM = "2"
    TYPE_COMMISSION_CPC = "1"
    TYPE_COMMISSION_CPM = "2"

    GENDER_MAN = 0
    GENDER_WOMEN = 1

    APP_KEY_DISABLE = 1

    COST_MAX = 999999999

    REDIS_CODE_HINCRBYFLOAT = 1
    REDIS_CODE_HSET = 2

    SDK_VERSION = 110


    //内存数据库选择
    CPM_ADINFO = 1
    CPM_ADSTAT = 2
    CPT_ADINFO = 3
    CPT_ADSTAT = 4
    PRELOAD_ADINFO = 5
    ADMODE_NUM = 6

)
